version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python3 /usr/src/app/app.py
    #command: tail -f /usr/src/app/requirements.txt
    # runtime: nvidia
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app
    restart: always
